# Hulk Hubot, a Hubot for our private IRC channel.
#  docker build -t hulkhubot ..
#  docker build -t hulkhubot:release .
#  docker run -d hulkhubot:release

FROM hulkhubot:latest
MAINTAINER mcoms

ENV HUBOT_IRC_ROOMS ##channel
ENV HUBOT_IRC_NICKSERV_USERNAME username
ENV HUBOT_IRC_NICKSERV_PASSWORD password
